# Array Shapes and Axes

---

**Question:**  
What does the term **axis** refer to in NumPy?

1. The number of dimensions in an array.
2. The total number of elements in an array.
3. The direction along which an operation is performed on an array.
4. The shape of an array.

**Answer:**   3

In NumPy, an axis refers to a specific dimension or direction along which operations can be applied to an array.

---

**Question:**  
How many axes does a **1D array** have?
1. 0
2. 1
3. 2
4. It depends on the length of the array.

**Answer:**   2

A **1D array** has only a single axis, which represents the single dimension of the array.

---

**Question:**  
Which keyword argument is used to specify the axis along which a mathematical operation is performed in NumPy?

1. axes
2. direction
3. axis
4. dimension

**Answer:**   3

The **axis** keyword argument is used to specify the axis along which a mathematical operation is performed in NumPy functions.

---

**Question:**  
What is **broadcasting** in NumPy?
1. The process of creating new elements in an array.
2. The process of dividing one array into multiple smaller arrays.
3. The process of collapsing an array into a single scalar value.
4. The process of adjusting the shape of arrays to perform operations on them.

**Answer:**   4

**Broadcasting** is the process in NumPy where arrays with different shapes are transformed or adjusted suitably to perform operations on them.

---

**Question:**  
In broadcasting, which dimension(s) of an array can be expanded to match the shape of another array?

1. Only the dimensions with size 1
2. Any dimension
3. Dimensions with different names
4. None of the above

**Answer:**   1

Broadcasting only allows dimensions with a **size of 1** to be expanded or replicated to match the shape of another array.

---

**Question:**  
Which function can be used to perform mathematical operations along a **specified axis** in an array?

1. `numpy.sum()`
2. `numpy.mean()`
3. `numpy.max()`
4. All of the above

**Answer:**   4

Functions like `numpy.sum()`, `numpy.mean()`, and `numpy.max()` can all be used with the axis parameter to perform mathematical operations along a specified axis in an array.

---

**Question:**  
What is the output of the following snippet code?
```python
import numpy as np
x = np.array([
    [[5, 3, 7, 1, 2],
     [2, 6, 4, 6 ,3]],
    [[6, 1, 5, 1, 8],
     [4, 3, 2, 0, 9],]
])
print(x.max(axis=2))
```

1.
```python
[[7 6]
 [8 9]]
```
2.
```python
[[7 6]
 [9 8]]
```
3.
```python
[[8 9]
 [7 6]]
```
4.
```python
[[9 8]
 [7 6]]
```


**Answer:**  1

Shape of this array is (2, 2, 5). Method `x.max(axis=2)` collapse and delete the third dimension (axis=2) and result array has shape (2, 2) with each value in the new array equal to the max of the corresponding collapsed values.

---

**Question:**  
Why is the speed of `numpy.flatten()` generally slower than `numpy.ravel()`?

1. `numpy.flatten()` creates a copy of the array and then flattens it, resulting in slower performance.
2. `numpy.ravel()` creates a copy of the array and then flattens it, resulting in slower performance.
3. `numpy.flatten()` operates in-place and modifies the original array, leading to slower performance.
4. `numpy.ravel()` operates in-place and modifies the original array, leading to slower performance.

**Answer:**   1

The `numpy.flatten()` function creates a **copy** of the array and then flattens it. This extra step of making a copy results in slower performance compared to `numpy.ravel()`, which does not create a copy but instead returns a **flattened view** of the original array. As a result, `numpy.ravel()` is generally faster than `numpy.flatten()`.

---