# Indexing and Filter (MCQ)

---

**Question:**

Accessing a single element or a group of elements in an array by specifying their index or indices in NumPy, it is referred to as:

1. Indexing
2. Slicing
3. Advanced indexing
4. Field access

**Answer:**  1

**Indexing** in NumPy involves accessing elements by specifying their indices using square brackets.

---

**Question:**

**Slicing** in NumPy refers to:

1. Accessing a single element of an array
2. Accessing a subset of elements in an array by specifying a range of indices using the colon `(:)` operator.
3. Accessing a field within a structured array
4. Accessing elements based on Boolean mask

**Answer:**  2

**Slicing** involves specifying a range of indices to access a subset of elements in an array using the colon `(:)` operator.

---

**Question:**

NumPy **basic slicing** creates a:

1. Copy of the array
2. New array with flattened dimensions
3. Boolean mask
4. View of the array

**Answer:**  4

**Basic slicing** in NumPy creates a **view** (not a copy) of the original array.

---

**Question:**

What is the difference between `x[2]` and `x[0:2]` (`x` is a numpy ndarray)?

1. Indexing `x[2]` returns the entire **column** with index 2 of the array, while slicing `x[0:2]` returns a specific subset of rows from index 0 to 1.

2. Slicing `x[2]` returns the entire **column** with index 2 of the array, while indexing `x[0:2]` returns a specific subset of rows from index 0 to 1.

3. Indexing `x[2]` returns the entire **row** with index 2 of the array, while slicing `x[0:2]` returns a specific subset of rows from index 0 to 1.

4. Slicing `x[2]` returns the entire **row** with index 2 of the array, while indexing `x[0:2]` returns a specific subset of rows from index 0 to 1.


**Answer:** 3

Indexing `x[2]` returns the entire **row** with index 2 of the array, while slicing `x[0:2]` returns a specific subset of rows from index 0 to 1.

---

**Question:**

NumPy **Boolean** array indexing always returns:

1. A view of the data
2. A copy of the data
3. A flattened array
4. A Boolean mask

**Answer:** 2

Boolean array indexing in NumPy always returns a **copy** of the data, unlike basic slicing which returns a view.

---

**Question:**

How many types of **advanced indexin**g are there in NumPy?

1. One
2. Two
3. Three
4. Four

**Answer:** 2

The two types of advanced indexing in NumPy are **integer array** indexing and **Boolean array** indexing.

---

**Question:**

In NumPy, which operators can be used to combine Boolean arrays to create complex masks?

1. `and, or, not`
2. `+, -`
3. `*, /`
4. `&, |, ~`

**Answer:** 4

In NumPy, the binary operators `&`, `|` and `~` can be used to combine Boolean arrays **element-wise** to create complex masks.

---

**Question:**

Which of the following statements is **true**?

1. Basic slicing always returns a **copy** of the array.
2. Advanced indexing always returns a **view** of the array.
3. Advanced indexing always returns a **copy** of the array.
4. Both basic slicing and advanced indexing always return a **view** of the array.

**Answer:**  3

Advanced indexing always returns a copy of the data contrast with basic slicing that returns a view.

---

**Question:**

Consider the following snippet code:
```python
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[[0, 2]])
```
Which of the following is the result of the above code?

1.
```python
30
```

2.
```python
[[10 20 30]
 [40 50 60]
 [70 80 90]]
```

3.
```python
[[10 20 30]
 [40 50 60]]
```

4.
```python
[[10 20 30]
 [70 80 90]]
```

**Answer:** 4

`x[[0, 2]]` is advanced indexing and returns a copy of row 0 and row 2 of array `x`:

```python
[[10 20 30]
 [70 80 90]]
 ```

---